package main

import (
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv" // For .env file loading

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	"video-service/docs" // docs is generated by Swag CLI
	"video-service/internal/db"
	"video-service/internal/handlers"
)

// @title Video Service API
// @version 1.0
// @description This is a sample video streaming service.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @schemes http

func main() {
	// Load .env file. If it doesn't exist, use default environment variables.
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, using default environment variables or expecting them to be set externally.")
	}

	mongoDBURI := os.Getenv("MONGO_DB_URI")
	mongoDBName := os.Getenv("MONGO_DB_NAME")
	serverAddress := os.Getenv("SERVER_ADDRESS")

	if mongoDBURI == "" {
		mongoDBURI = "mongodb://admin:password@localhost:27017"
	}
	if mongoDBName == "" {
		mongoDBName = "video_service_db"
	}
	if serverAddress == "" {
		serverAddress = ":8080"
	}

	// Initialize MongoDB connection
	if err := db.ConnectDB(mongoDBURI, mongoDBName); err != nil {
		log.Fatalf("Failed to connect to MongoDB: %v", err)
	}
	defer db.DisconnectDB()

	r := gin.Default()

	// Setup Swagger UI route
	docs.SwaggerInfo.BasePath = "/" // Make sure this matches your API's base path
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "pong",
		})
	})

	// Admin routes
	adminRoutes := r.Group("/admin")
	{
		adminRoutes.POST("/videos", handlers.CreateVideo)
		adminRoutes.GET("/videos/:id", handlers.GetVideoByID)
		adminRoutes.PUT("/videos/:id", handlers.UpdateVideo)
		adminRoutes.DELETE("/videos/:id", handlers.DeleteVideo)
		adminRoutes.GET("/videos", handlers.ListVideos)
	}

	log.Printf("Server starting on %s", serverAddress)
	log.Printf("Swagger UI available at http://localhost%s/swagger/index.html", serverAddress)
	if err := r.Run(serverAddress); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
