package main

import (
	"log"

	"admin-service/handlers"
	"admin-service/routes"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "admin-service/docs" // docs is generated by Swag CLI
)

// @title Admin Service API
// @version 1.0
// @description This is an admin service for managing users and videos.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8082
// @BasePath /api/v1
func main() {
	r := gin.Default()

	// Initialize handlers (placeholder for now, can be expanded with DB connections etc.)
	userHandler := handlers.NewUserHandler()   // Placeholder for now
	videoHandler := handlers.NewVideoHandler() // Placeholder for now

	// Setup routes
	routes.SetupRoutes(r, userHandler, videoHandler)

	// Swagger endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Println("Server starting on port 8082...")
	if err := r.Run(":8082"); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}
